#Requires -Version 7.0
<#
.SYNOPSIS
    Claude Harness - Session Initialization Script (PowerShell)
.DESCRIPTION
    Project: kubeopt
    Generated by claude-harness
.NOTES
    Run this at the start of each Claude Code session
#>

$ErrorActionPreference = 'Continue'

# Configuration
$HarnessDir = ".claude-harness"
$ConfigFile = "$HarnessDir/config.json"

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

# Header
Write-Host ""
Write-ColorOutput "=======================================================" "Blue"
Write-ColorOutput "  CLAUDE HARNESS - Session Initialization" "Blue"
Write-ColorOutput "  Project: kubeopt" "Blue"
Write-ColorOutput "=======================================================" "Blue"
Write-Host ""

# Check harness exists
if (-not (Test-Path $ConfigFile)) {
    Write-ColorOutput "ERROR: Harness not initialized. Run 'claude-harness init' first." "Red"
    exit 1
}

# 1. Git Status
Write-ColorOutput "[1/6] GIT STATUS" "Yellow"
if (Get-Command git -ErrorAction SilentlyContinue) {
    if (Test-Path ".git") {
        $branch = git branch --show-current 2>$null
        $protectedBranches = @("main", "master")

        if ($protectedBranches -contains $branch) {
            Write-ColorOutput "  WARNING: On protected branch '$branch'!" "Red"
            Write-ColorOutput "  Create a feature branch before making changes." "Red"
        } else {
            Write-ColorOutput "  Branch: $branch" "Green"
        }

        # Check for uncommitted changes
        $status = git status --porcelain 2>$null
        if ($status) {
            Write-ColorOutput "  Uncommitted changes detected" "Yellow"
        }
    } else {
        Write-ColorOutput "  Not a git repository" "Yellow"
    }
} else {
    Write-ColorOutput "  Git not available" "Yellow"
}
Write-Host ""

# 2. Virtual Environment
Write-ColorOutput "[2/6] VIRTUAL ENVIRONMENT" "Yellow"
$venvActivate = "venv/Scripts/Activate.ps1"
if (Test-Path $venvActivate) {
    try {
        & $venvActivate
        Write-ColorOutput "  Activated: venv" "Green"
    } catch {
        Write-ColorOutput "  Failed to activate venv: $_" "Red"
    }
} else {
    Write-ColorOutput "  Virtual environment not found at venv" "Red"
    Write-ColorOutput "  Run: python -m venv venv" "Yellow"
}
Write-Host ""

# 3. Application Status
Write-ColorOutput "[3/6] APPLICATION" "Yellow"
$port = 5000
$healthUrl = "http://localhost:$port/api/v1/health"

try {
    $response = Invoke-WebRequest -Uri $healthUrl -TimeoutSec 5 -UseBasicParsing -ErrorAction Stop
    Write-ColorOutput "  App running on port $port" "Green"
    $appRunning = $true
} catch {
    Write-ColorOutput "  App not running on port $port" "Yellow"
    $appRunning = $false

    $startApp = Read-Host "  Start the application? (y/N)"
    if ($startApp -eq 'y' -or $startApp -eq 'Y') {
        # Load environment from .env
        if (Test-Path ".env") {
            Get-Content ".env" | ForEach-Object {
                if ($_ -match '^([^#][^=]+)=(.*)$') {
                    [Environment]::SetEnvironmentVariable($matches[1], $matches[2], 'Process')
                }
            }
        }
        Write-ColorOutput "  Starting: python run.py" "Yellow"
        Start-Process -FilePath "pwsh" -ArgumentList "-Command", "python run.py" -WindowStyle Hidden
        Start-Sleep -Seconds 3

        try {
            $response = Invoke-WebRequest -Uri $healthUrl -TimeoutSec 5 -UseBasicParsing -ErrorAction Stop
            Write-ColorOutput "  App started successfully" "Green"
        } catch {
            Write-ColorOutput "  Failed to start. Check logs." "Red"
        }
    }
}
Write-Host ""

# 4. Database Connection
Write-ColorOutput "[4/6] DATABASE (postgresql)" "Yellow"
try {
    $result = python -c @"
try:
    from app import create_app
    app = create_app()
    with app.app_context():
        from app.extensions import db
        db.engine.connect()
        print('Connected successfully')
except Exception as e:
    print(f'Connection failed: {e}')
"@
    Write-ColorOutput "  $result" "Green"
} catch {
    Write-ColorOutput "  Could not verify database connection" "Yellow"
}
Write-Host ""

# 5. Test Status
Write-ColorOutput "[5/6] TESTS" "Yellow"
if (Get-Command pytest -ErrorAction SilentlyContinue) {
    try {
        $testResult = pytest tests/unit/ -q --tb=no 2>&1 | Select-Object -Last 3
        Write-Host "  $testResult"
    } catch {
        Write-ColorOutput "  Could not run tests" "Yellow"
    }
} else {
    Write-ColorOutput "  pytest not available" "Yellow"
}
Write-Host ""

# 6. Session Progress
Write-ColorOutput "[6/6] SESSION PROGRESS" "Yellow"
$progressFile = "$HarnessDir/progress.md"
$featuresFile = "$HarnessDir/features.json"

if (Test-Path $progressFile) {
    Write-Host ""
    Write-ColorOutput "--- Last Session Summary ---" "Blue"
    $content = Get-Content $progressFile -Raw
    # Show the Last Session section
    if ($content -match '(?s)## Last Session.*?(?=## Previous|$)') {
        $matches[0] -split "`n" | Select-Object -First 25 | ForEach-Object { Write-Host $_ }
    }
    Write-ColorOutput "----------------------------" "Blue"
}

if (Test-Path $featuresFile) {
    Write-Host ""
    $features = Get-Content $featuresFile | ConvertFrom-Json
    Write-ColorOutput "  Current Phase: $($features.current_phase)" "Green"

    $inProgress = $features.features | Where-Object { $_.status -eq "in_progress" } | Select-Object -First 1
    if ($inProgress) {
        Write-ColorOutput "  In Progress: $($inProgress.id): $($inProgress.name)" "Yellow"
    } else {
        $nextPending = $features.features | Where-Object { $_.status -eq "pending" } | Select-Object -First 1
        if ($nextPending) {
            Write-ColorOutput "  Next Pending: $($nextPending.id): $($nextPending.name)" "Blue"
        }
    }
}

Write-Host ""
Write-ColorOutput "=======================================================" "Blue"
Write-ColorOutput "  Ready to work!" "Green"
Write-ColorOutput "  Read .claude-harness/progress.md for full context" "Blue"
Write-ColorOutput "=======================================================" "Blue"
Write-Host ""
