#!/bin/bash
# Claude Harness - Session Initialization Script
# Generated by claude-harness
# NOTE: Most settings are read from .claude-harness/config.json at runtime

set -e

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

HARNESS_DIR=".claude-harness"
CONFIG="$HARNESS_DIR/config.json"

# Check harness exists
if [[ ! -f "$CONFIG" ]]; then
    echo -e "${RED}ERROR: Harness not initialized. Run 'claude-harness init' first.${NC}"
    exit 1
fi

# Read config values (with fallback defaults)
if command -v jq &> /dev/null; then
    PROJECT_NAME=$(jq -r '.project_name // "project"' "$CONFIG")
    PORT=$(jq -r '.startup.port // 8000' "$CONFIG")
    HEALTH_ENDPOINT=$(jq -r '.startup.health_endpoint // "/health"' "$CONFIG")
    START_CMD=$(jq -r '.startup.start_command // "python main.py"' "$CONFIG")
    VENV_PATH=$(jq -r '.paths.venv // "venv"' "$CONFIG")
    ENV_FILE=$(jq -r '.paths.env_file // ".env"' "$CONFIG")
    DATABASE=$(jq -r '.stack.database // ""' "$CONFIG")
    LANGUAGE=$(jq -r '.stack.language // "python"' "$CONFIG")
    PROTECTED=$(jq -r '.git.protected_branches | join(" ")' "$CONFIG" 2>/dev/null || echo "main master")
else
    # Fallback if jq not available
    PROJECT_NAME="project"
    PORT=8000
    HEALTH_ENDPOINT="/health"
    START_CMD="python main.py"
    VENV_PATH="venv"
    ENV_FILE=".env"
    DATABASE=""
    LANGUAGE="python"
    PROTECTED="main master"
fi

echo ""
echo -e "${BLUE}=======================================================${NC}"
echo -e "${BLUE}  CLAUDE HARNESS - Session Initialization${NC}"
echo -e "${BLUE}  Project: $PROJECT_NAME${NC}"
echo -e "${BLUE}=======================================================${NC}"
echo ""

# 1. Git Status
echo -e "${YELLOW}[1/6] GIT STATUS${NC}"
if command -v git &> /dev/null && [[ -d ".git" ]]; then
    BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

    if [[ " $PROTECTED " =~ " $BRANCH " ]]; then
        echo -e "${RED}  WARNING: On protected branch '$BRANCH'!${NC}"
        echo -e "${RED}  Create a feature branch before making changes.${NC}"
    else
        echo -e "${GREEN}  Branch: $BRANCH${NC}"
    fi

    # Check for uncommitted changes
    if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
        echo -e "${YELLOW}  Uncommitted changes detected${NC}"
    fi
else
    echo -e "${YELLOW}  Git not available or not a repository${NC}"
fi
echo ""

# 2. Virtual Environment
echo -e "${YELLOW}[2/6] VIRTUAL ENVIRONMENT${NC}"
if [[ "$LANGUAGE" == "python" ]] && [[ -n "$VENV_PATH" ]]; then
    VENV_ACTIVATE="$VENV_PATH/bin/activate"
    if [[ -f "$VENV_ACTIVATE" ]]; then
        source "$VENV_ACTIVATE" 2>/dev/null
        echo -e "${GREEN}  Activated: $VENV_PATH${NC}"
    else
        echo -e "${RED}  Virtual environment not found at $VENV_PATH${NC}"
        echo -e "${YELLOW}  Run: python -m venv $VENV_PATH${NC}"
    fi
else
    echo -e "${GREEN}  No virtual environment needed${NC}"
fi
echo ""

# 3. Application Status
echo -e "${YELLOW}[3/6] APPLICATION${NC}"
HEALTH_URL="http://localhost:$PORT$HEALTH_ENDPOINT"

if curl -s "$HEALTH_URL" > /dev/null 2>&1; then
    echo -e "${GREEN}  App running on port $PORT${NC}"
    APP_RUNNING=true
else
    echo -e "${YELLOW}  App not running on port $PORT${NC}"
    APP_RUNNING=false

    # Offer to start
    read -p "  Start the application? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [[ -n "$ENV_FILE" ]] && [[ -f "$ENV_FILE" ]]; then
            export $(grep -v '^#' "$ENV_FILE" | xargs) 2>/dev/null
        fi
        echo -e "${YELLOW}  Starting: $START_CMD${NC}"
        LOG_FILE="/tmp/${PROJECT_NAME// /_}.log"
        nohup $START_CMD > "$LOG_FILE" 2>&1 &
        sleep 3

        if curl -s "$HEALTH_URL" > /dev/null 2>&1; then
            echo -e "${GREEN}  App started successfully${NC}"
        else
            echo -e "${RED}  Failed to start. Check $LOG_FILE${NC}"
        fi
    fi
fi
echo ""

# 4. Database Connection
echo -e "${YELLOW}[4/6] DATABASE${NC}"
if [[ -n "$DATABASE" ]]; then
    echo -e "  Checking $DATABASE connection..."
    # Generic database check - tries common Python patterns
    python3 -c "
import sys
try:
    # Try Flask pattern first
    from app import create_app, db
    app = create_app()
    with app.app_context():
        db.engine.connect()
        print('  Connected successfully')
except ImportError:
    try:
        # Try direct SQLAlchemy
        from db import engine
        engine.connect()
        print('  Connected successfully')
    except:
        print('  Could not verify connection (check manually)')
except Exception as e:
    print(f'  Connection issue: {e}')
" 2>/dev/null || echo -e "${YELLOW}  Could not verify database connection${NC}"
else
    echo -e "${GREEN}  No database configured${NC}"
fi
echo ""

# 5. Test Status
echo -e "${YELLOW}[5/6] TESTS${NC}"
if command -v pytest &> /dev/null; then
    # Quick test collection (no execution)
    TEST_COUNT=$(pytest --collect-only -q 2>/dev/null | tail -1 | grep -oE "[0-9]+ test" || echo "? tests")
    echo -e "  Found: ${GREEN}$TEST_COUNT${NC}"
    echo -e "  Run: pytest tests/ -v --tb=short"
else
    echo -e "${YELLOW}  pytest not available${NC}"
fi
echo ""

# 6. Session Progress
echo -e "${YELLOW}[6/6] SESSION PROGRESS${NC}"
PROGRESS_FILE="$HARNESS_DIR/progress.md"
FEATURES_FILE="$HARNESS_DIR/features.json"

if [[ -f "$PROGRESS_FILE" ]]; then
    echo ""
    echo -e "${BLUE}--- Last Session Summary ---${NC}"
    # Show relevant sections from progress.md
    sed -n '/^## Last Session/,/^## Previous/p' "$PROGRESS_FILE" | head -25
    echo -e "${BLUE}----------------------------${NC}"
fi

if [[ -f "$FEATURES_FILE" ]] && command -v jq &> /dev/null; then
    echo ""
    CURRENT_PHASE=$(jq -r '.current_phase' "$FEATURES_FILE")
    echo -e "  Current Phase: ${GREEN}$CURRENT_PHASE${NC}"

    IN_PROGRESS=$(jq -r '.features[] | select(.status == "in_progress") | "\(.id): \(.name)"' "$FEATURES_FILE" 2>/dev/null | head -1)
    if [[ -n "$IN_PROGRESS" ]]; then
        echo -e "  In Progress: ${YELLOW}$IN_PROGRESS${NC}"
    else
        NEXT_PENDING=$(jq -r '.features[] | select(.status == "pending") | "\(.id): \(.name)"' "$FEATURES_FILE" 2>/dev/null | head -1)
        if [[ -n "$NEXT_PENDING" ]]; then
            echo -e "  Next Pending: ${BLUE}$NEXT_PENDING${NC}"
        fi
    fi
fi

echo ""
echo -e "${BLUE}=======================================================${NC}"
echo -e "${GREEN}  Ready to work!${NC}"
echo -e "${BLUE}  Read .claude-harness/progress.md for full context${NC}"
echo -e "${BLUE}=======================================================${NC}"
echo ""
